### ISSUE TITLE
dMRI recon tran_shi_2015 not working

### ISSUE THREAD

**Issue by mblesac** [dmritrekker/trekker#31]
Dear experts,

I'm trying to use trekker to do the dMRI reconstruction based on the Tran and Shi model by running the following command:

`trekker_linux_x64_v1.0.0-rc2 dMRI recon tran_shi_2015 --gradient bvecs bvals --mask sub-9001_ses-01_space-dwi_brain-mask.nii.gz sub-9001_ses-01_space-dwi_desc-preproc_dwi.nii.gz fod.nii map.nii.gz` 

However, nothing happens, not an error or anything (and any message, I tried all the verbose options). Any clue what could be the reason for this? Thanks in advance!

Best regards,

Manuel

**Comment by baranaydogan** [comment]
Hi,

I was able to reproduce this which I believe was related to the linking of the optimization library we were using in nibrary. The issue is fixed in the opened branch for this issue, and will be included in release candidate 3 (rc3).

The compilation of Trekker rc3 is easier than earlier versions. We now bundled nibrary inside Trekker. So you only need to pull Trekker (issue branch) and compile. It will download and compile the matching nibrary internally, so the above mention patch will be applied without the need for separately installing nibrary (again).

I also added a short info text in the terminal telling that it is reading the dMRI data in the beginning, which can take quite a long time (tens of seconds).

Lastly, if you are using Linux, the attach binary file here, [trekker_v1.0.0-rc3_d679a2c.zip](https://github.com/user-attachments/files/18416655/trekker_v1.0.0-rc3_d679a2c.zip), should work in most systems.

**Comment by mblesac** [comment]
Hi,

Thanks for your reply!

I downloaded the binary file and run it, but still doesn't produce any output. However, it displays the following message:

```
trekker_v1.0.0-rc3_d679a2c dMRI recon tran_shi_2015 --gradient bvecs bvals --mask sub-9001_ses-01_space-dwi_brain-mask.nii.gz --verbose debug sub-9001_ses-01_space-dwi_desc-preproc_dwi.nii.gz fod.nii map.nii.gz

NIBRARY::DEBUG: PTT parameters cleared. [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/algorithms/ptt/algorithm_ptt_params.cpp line:172]
NIBRARY::DEBUG: Deconstructing pathway [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:34]
NIBRARY::DEBUG: Removing pathway rules [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:36]
NIBRARY::DEBUG: Removing seed rule [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:53]
NIBRARY::DEBUG: seeds deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:63]
NIBRARY::DEBUG: img_mask deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:68]
NIBRARY::DEBUG: img_label deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:73]
NIBRARY::DEBUG: img_pvf deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:78]
NIBRARY::DEBUG: surfData deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:86]
NIBRARY::DEBUG: surf deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:91]
NIBRARY::DEBUG: sphCenter deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:96]
NIBRARY::DEBUG: pntLists deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:101]
NIBRARY::DEBUG: dirLists deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:106]
NIBRARY::DEBUG: data deleted [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:111]
NIBRARY::DEBUG: Internal source vectors cleared [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:130]
NIBRARY::DEBUG: Internal variables cleared [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:142]
NIBRARY::DEBUG: User inputs cleared [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:147]
NIBRARY::DEBUG: Pathway deconstructed [/home/baran/dev/trekker/build-static/external/nibrary_v0.3.0/src/dMRI/tractography/pathway/pathway.cpp line:152]
```

I also tried to install the other branches:

```
git clone https://github.com/dmritrekker/trekker
cd trekker 
git checkout build   ##or 31-dmri-recon-tran_shi_2015-not-working
sh build.sh  ##after editing it and adding the correct paths for gcc and g++
```

but I get the following error:

```
[ 28%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/geofile.cpp.o
[ 27%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/factory.cpp.o
[ 29%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/file_system.cpp.o
[ 29%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/environment.cpp.o
[ 30%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/line_stream.cpp.o
[ 31%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/logger.cpp.o
[ 32%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/numeric.cpp.o
[ 32%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/packed_arrays.cpp.o
[ 33%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/process.cpp.o
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp: In member function 'size_t GEO::GeoFile::read_size()':
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:26: error: expected ')' before 'PRIu64'
   49 | # define INT64_T_FMT "%" PRIu64
      |                          ^~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:326:36: note: in expansion of macro 'INT64_T_FMT'
  326 |             if(fscanf(ascii_file_, INT64_T_FMT "\n", &result) == 0) {
      |                                    ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:326:22: note: to match this '('
  326 |             if(fscanf(ascii_file_, INT64_T_FMT "\n", &result) == 0) {
      |                      ^
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:1: note: 'PRIu64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
   48 | # include <inttypes.h>
  +++ |+#include <cinttypes>
   49 | # define INT64_T_FMT "%" PRIu64
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:22: warning: spurious trailing '%' in format [-Wformat=]
   49 | # define INT64_T_FMT "%" PRIu64
      |                      ^~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:326:36: note: in expansion of macro 'INT64_T_FMT'
  326 |             if(fscanf(ascii_file_, INT64_T_FMT "\n", &result) == 0) {
      |                                    ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:23: note: format string is defined here
   49 | # define INT64_T_FMT "%" PRIu64
      |                       ^
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:22: warning: too many arguments for format [-Wformat-extra-args]
   49 | # define INT64_T_FMT "%" PRIu64
      |                      ^~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:326:36: note: in expansion of macro 'INT64_T_FMT'
  326 |             if(fscanf(ascii_file_, INT64_T_FMT "\n", &result) == 0) {
      |                                    ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp: In member function 'void GEO::GeoFile::write_size(size_t)':
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:26: error: expected ')' before 'PRIu64'
   49 | # define INT64_T_FMT "%" PRIu64
      |                          ^~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:345:37: note: in expansion of macro 'INT64_T_FMT'
  345 |             if(fprintf(ascii_file_, INT64_T_FMT "\n", x) == 0) {
      |                                     ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:345:23: note: to match this '('
  345 |             if(fprintf(ascii_file_, INT64_T_FMT "\n", x) == 0) {
      |                       ^
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:26: note: 'PRIu64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
   49 | # define INT64_T_FMT "%" PRIu64
      |                          ^~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:345:37: note: in expansion of macro 'INT64_T_FMT'
  345 |             if(fprintf(ascii_file_, INT64_T_FMT "\n", x) == 0) {
      |                                     ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:22: warning: spurious trailing '%' in format [-Wformat=]
   49 | # define INT64_T_FMT "%" PRIu64
      |                      ^~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:345:37: note: in expansion of macro 'INT64_T_FMT'
  345 |             if(fprintf(ascii_file_, INT64_T_FMT "\n", x) == 0) {
      |                                     ^~~~~~~~~~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:23: note: format string is defined here
   49 | # define INT64_T_FMT "%" PRIu64
      |                       ^
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:49:22: warning: too many arguments for format [-Wformat-extra-args]
   49 | # define INT64_T_FMT "%" PRIu64
      |                      ^~~
/EBC/local/trekker-rc1/trekker/build-static/external/nibrary_v0.3.0/external/geogram/src/lib/geogram/basic/geofile.cpp:345:37: note: in expansion of macro 'INT64_T_FMT'
  345 |             if(fprintf(ascii_file_, INT64_T_FMT "\n", x) == 0) {
      |                                     ^~~~~~~~~~~
[ 34%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/process_unix.cpp.o
[ 34%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/process_win.cpp.o
[ 35%] Building CXX object src/lib/geogram/CMakeFiles/geogram.dir/basic/progress.cpp.o
gmake[8]: *** [src/lib/geogram/CMakeFiles/geogram.dir/build.make:272: src/lib/geogram/CMakeFiles/geogram.dir/basic/geofile.cpp.o] Error 1
gmake[8]: *** Waiting for unfinished jobs....
gmake[7]: *** [CMakeFiles/Makefile2:178: src/lib/geogram/CMakeFiles/geogram.dir/all] Error 2
gmake[6]: *** [Makefile:156: all] Error 2
gmake[5]: *** [external/CMakeFiles/build_geogram.dir/build.make:87: external/geogram/src/build_geogram-stamp/build_geogram-build] Error 2
gmake[4]: *** [CMakeFiles/Makefile2:210: external/CMakeFiles/build_geogram.dir/all] Error 2
gmake[3]: *** [Makefile:136: all] Error 2
gmake[2]: *** [external/CMakeFiles/build_nibrary.dir/build.make:92: external/nibrary/src/build_nibrary-stamp/build_nibrary-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:153: external/CMakeFiles/build_nibrary.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Best regards,

Manuel

**Comment by baranaydogan** [comment]
There is little check regarding the input files and their formats at the moment. I am guessing that your issue is probably because Trekker was not able to read the bvecs and bvals files. In that case, it does not write any error message, which should be added. Here, [b.zip](https://github.com/user-attachments/files/18425714/b.zip), is a set of bvals and bvecs files that Trekker works with. It also will not work if the number of bvals and bvecs does not match for example. (I will add error messages about these.) But let's first check and confirm that this is issue.

**Comment by baranaydogan** [comment]
Sorry, I have not noticed before, instead of:

--gradient bvecs bvals

try

--gradient bvals bvecs

I will add error messages in the code.

**Comment by mblesac** [comment]
Ah, sorry for the confusion, now it works perfectly! thanks!

**Comment by baranaydogan** [comment]
Great!
